<a href="https://colab.research.google.com/github/srishti-git1110/Simple_NN_in_PyTorch/blob/main/Autograd_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [8]:
x = torch.tensor([1,2,3], requires_grad=True, dtype=torch.float)
y = x**2
z = y.mean()
print(x.grad) ; print(y.grad)
z.backward()  #backpropates gradients
print(x.grad) #now x has some gradient basically dz/dx
print(y.grad) #warning msg below makes it clear why this is none


None
None
tensor([0.6667, 1.3333, 2.0000])
None


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


In [9]:
#theoretically the grad = 2xi/3
2*x/3

tensor([0.6667, 1.3333, 2.0000], grad_fn=<DivBackward0>)

so basically we can set our weights as tensors that require gradients & then do a forward pass to calc loss, and then backward() to pass gradients to weights 7 biases.

In [15]:
#illustrates the use of no_grad(), basically it's for efficiency
with torch.no_grad():
  z = (x**3 + x**2).mean()
z
z.backward()
x.grad()

RuntimeError: ignored

In [14]:
z = (x**3 + x**2).mean()
z.backward()
x.grad

tensor([ 2.3333,  6.6667, 13.0000])